// vue-notes/src/components/Sidebar.vue
<script setup lang="ts">
import { computed, ComputedRef } from "vue";

import { Note, useAppStore } from "@/store";

const store = useAppStore();
const notes: ComputedRef<Note[]> = computed(() => store.getters.notes);

const createNote = () => store.commit("createNote");
const setCurrentNote = (note: Note) => store.commit("setCurrentNote", note);
const removeNote = (note: Note) => store.commit("removeNote", note);
</script>

<template>
  <div id="sidebar">
    <button @click="createNote">New Note</button>
    <table className="notes-list">
      <tbody>
        <tr v-for="note in notes" :key="note.id">
          <td @click="setCurrentNote(note)" v-text="note.title"></td>
          <td className="actions" @click="removeNote(note)">[x]</td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

<style scoped>
#sidebar {
  flex-grow: 0;
  padding: 20px;
  max-width: 15em;
}

button {
  width: 100%;
}

.notes-list {
  width: 100%;
}

.notes-list .actions {
  text-align: right;
}
</style>

// react-notes/src/components/Sidebar.tsx
import {
  selectNotes,
  setCurrentNote,
  createNote,
  useAppDispatch,
  useAppSelector,
  removeNote,
} from "../store";

import "./Sidebar.css";

function Sidebar() {
  const dispatch = useAppDispatch();
  const notes = useAppSelector(selectNotes);

  return (
    <div id="Sidebar">
      <button onClick={() => dispatch(createNote())}>New Note</button>
      <table className="notes-list">
        <tbody>
          {notes.map((note) => (
            <tr key={note.id}>
              <td onClick={() => dispatch(setCurrentNote(note))}>
                {note.title}
              </td>
              <td
                className="actions"
                onClick={() => dispatch(removeNote(note))}
              >
                [x]
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

export default Sidebar;
